/**
 * Manual test for Tag Service
 * This file demonstrates how the tag organization feature works
 * 
 * To run this test manually:
 * 1. Ensure the application is running
 * 2. Import files and observe tag normalization
 * 3. Call the API endpoints to verify functionality
 */

// Example 1: Normalizing tags with synonym checking
const testNormalizeTags = async () => {
  const response = await fetch('http://localhost:8000/api/tags/normalize', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      tags: ['報告', '学习资料', '技朮文档', '重要', '緊急']
    })
  });
  
  const result = await response.json();
  console.log('Normalized tags:', result.data);
  // Expected: Tags will be matched against preset tags
  // - "報告" -> "报告" (if similarity >= 80%)
  // - "学习资料" -> "学习" (if similarity >= 80%)
  // - "技朮文档" -> "技术" (if similarity >= 80%)
  // - "重要" -> "重要" (exact match)
  // - "緊急" -> "紧急" (if similarity >= 80%)
};

// Example 2: Getting the merged tag library
const testGetTagLibrary = async () => {
  const response = await fetch('http://localhost:8000/api/tags/library');
  const result = await response.json();
  console.log('Tag library:', result.data);
  // Expected: Array of all unique tags from preset + database
};

// Example 3: Checking cache status
const testGetCacheStatus = async () => {
  const response = await fetch('http://localhost:8000/api/tags/cache/status');
  const result = await response.json();
  console.log('Cache status:', result.data);
  // Expected: { cached: true/false, age: number, count: number }
};

// Example 4: Clearing cache
const testClearCache = async () => {
  const response = await fetch('http://localhost:8000/api/tags/cache/clear', {
    method: 'POST'
  });
  const result = await response.json();
  console.log('Cache cleared:', result.data);
};

// Example 5: File import with auto-tagging
// When you import a file through the UI or API, tags will be automatically normalized
const testFileImportWithTags = async (filePath: string) => {
  const formData = new FormData();
  formData.append('file', filePath);
  
  const response = await fetch('http://localhost:8000/api/files/save-file', {
    method: 'POST',
    body: formData
  });
  
  const result = await response.json();
  console.log('File imported with normalized tags:', result.data.tags);
  // Tags generated by LLM will be checked against tag library
  // Similar tags will be replaced with existing ones
};

// Example 6: Manual tag update
const testUpdateFileTags = async (fileId: string, newTags: string[]) => {
  const response = await fetch('http://localhost:8000/api/files/update', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      file_id: fileId,
      tags: newTags
    })
  });
  
  const result = await response.json();
  console.log('Updated file tags (normalized):', result.data.tags);
  // Tags will be normalized before saving to database
};

// Configuration example
const exampleConfig = {
  "presetTags": [
    // Common document categories
    "工作", "学习", "项目", "会议", "报告", "总结",
    // Media and content types  
    "图片", "视频", "音频", "文档", "演示",
    // General classifications
    "重要", "紧急", "参考", "归档", "草稿",
    // Domain specific
    "技术", "设计", "营销", "财务", "法律"
  ],
  "autoTagEnabled": true,
  "tagSummaryMaxLength": 1000
};

console.log('Example config.json preset tags:', exampleConfig);

// Similarity algorithm demonstration
function demonstrateLevenshtein() {
  // Example similar tags that should match:
  const pairs = [
    ["報告", "报告"],     // Traditional vs Simplified Chinese
    ["技朮", "技术"],     // Typo vs correct
    ["緊急", "紧急"],     // Traditional vs Simplified
    ["学习资料", "学习"], // Compound vs simple
    ["會議", "会议"],     // Traditional vs Simplified
  ];
  
  console.log('Similar tag pairs that should match:');
  pairs.forEach(([a, b]) => {
    console.log(`  "${a}" <-> "${b}"`);
  });
}

export {
  testNormalizeTags,
  testGetTagLibrary,
  testGetCacheStatus,
  testClearCache,
  testFileImportWithTags,
  testUpdateFileTags,
  demonstrateLevenshtein
};
